{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizantalPodAutoscalar
metadata:
  name: {{ include "pricing-svc.fullname" . }}
  labels:
    {{- include "pricing-svc.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "pricing-svc.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300