{{- if and .Values.database.enabled (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pricing-svc.fullname" . }}-db
  labels:
    {{- include "pricing-svc.labels" . | nindent 4 }}
type: Opaque
stringData:
  dsn: {{ printf "postgresql://%s:%s@%s:%v/%s"
            .Values.database.user
            (required "database.password is required when not using existingSecret" .Values.database.password)
            (required "database.host is required" .Values.database.host)
            .Values.database.port
            .Values.database.name | quote }}
{{- end }}